---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fief-pv-redis-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Mi
